### PR TITLE
[WIP] Fix docker file to depend on golang image and update README.md

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
This patch is not ready yet since scaleway/golang image is not updated with latest 1.7.x atleast i can't pull it by any regular means. If i am missing something please correct me @scaleway-community/scaleway-minio .

**Comment by QuentinPerez** [comment]
Hi @harshavardhana,

Thank you for your PR, but at Scaleway we use Dockerfile to craft our [images](https://www.scaleway.com/imagehub/), thus we don't use it to start docker containers and we can't use `EXPOSE, CMD`.

Can you:
 - remove `EXPOSE`, `CMD`
 - `go get` a release version of Minio instead of `go get` the latest
 - add systemd service to start/launch Minio at the boot

 You can found more documentation [here](https://github.com/scaleway/image-builder)

Let me know if you need anything else 😊

**Comment by harshavardhana** [comment]
> go get a release version of Minio instead of go get the latest
> add systemd service to start/launch Minio at the boot

Even for this i can't proceed forward since Go 1.7 is the minimum requirement for Minio.i don't see where to get it from using scaleway/golang.

Also EXPOSE and CMD is used in accordance with images built for nats - https://github.com/scaleway-community/scaleway-nats/blob/master/Dockerfile#L26  - is this incorrect?

**Comment by harshavardhana** [comment]
@QuentinPerez can you let me know about the above comment?

**Pull request closed without merging**
